apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenoid-ui # kubectl get deployment backend - логи посмотреть как прошёл деплой
spec:
  replicas: 1 #количество копий POD
  selector:
    matchLabels:
      app: selenoid-ui #связываем deployment и pod
  template:
    metadata:
      labels:
        app: selenoid-ui #устанаваливаем лейбл на под
    spec:
      containers:
        - name: selenoid-ui
          image: aerokube/selenoid-ui:latest
          args: [ "--selenoid-uri", "http://selenoid:4444" ]
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: selenoid-ui
spec:
  selector:
    app: selenoid-ui #сервис который мы написали будет направлять трафик на поды у которых app = backend
  ports:
    - protocol: TCP
      port: 8080 # порт на котором работает сервис
      targetPort: 8080 # куда пересылать внутри пода (контейнер слушает этот порт)
  type: NodePort # ClusterIP (доступен только внутри кластера), NodePort (открывает порт на всех нодах кластера)