services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: nbank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nbank-network

  backend:
    image: nobugsme/nbank:preprod_version
    ports:
      - "4111:4111"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/nbank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      FRAUD_DETECTION_SERVICE_URL: http://host.docker.internal:8080
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4111/actuator/health" ]
      interval: 30s
      timeout: 20s
      retries: 20
      start_period: 160s
    networks:
      - nbank-network

  frontend:
    image: nobugsme/nbank-ui:preprod_version
    ports: # мы не открываем порт наружу, а даём доступ контейнерам в сети (для безопасности)
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - nbank-network

  selenoid:
    image: aerokube/selenoid:latest-release
    environment:
      DOCKER_API_VERSION: "1.44"
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/:/etc/selenoid/:ro
    command: [ "-container-network", "nbank-network" ]
    healthcheck:
      test: [
        "CMD",
        "wget",
        "-q",
        "--spider",
        "http://localhost:4444/ping"
      ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      frontend:
        condition: service_healthy
    networks:
      - nbank-network

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    ports:
      - "6567:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
    depends_on:
      selenoid:
        condition: service_healthy
    networks:
      - nbank-network

networks:
  nbank-network:
    name: nbank-network

volumes:
  postgres_data: