name: Run tests

#триггер
on: [ push, workflow_dispatch ]


jobs: # аналог этапов
  run-tests:
    name: Set up services (review apps) and run tests
    runs-on: ubuntu-latest
    steps: #шаги конкретной job
      - name: Checkout Repository #копируем файлы репозитория внутрь CI агента (раннера)
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up services
        run: cd infra/docker_compose && bash restart_docker.sh && cd ../..

      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      - name: Make Swagger Coverage executable
        run: chmod +x .swagger-coverage-commandline/bin/swagger-coverage-commandline

      - name: Run tests
        run: ./mvnw clean test -q
        env:
          APIBASEURL: http://localhost:4111
          UIBASEURL: http://frontend:80
          APIVERSION: /api/v1

      - name: Run Swagger coverage
        if: always()
        run: .swagger-coverage-commandline/bin/swagger-coverage-commandline -s http://localhost:4111/v3/api-docs -i target/swagger-coverage-output

      - name: Load tests report history
        uses: actions/checkout@v4
        continue-on-error: true
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: target/allure-results
          allure_history: allure-history

      - name: Build Swagger coverage report
        if: always()
        run: sudo cp swagger-coverage-report.html allure-history/${{ github.run_number }}

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Clean up services
        if: always()
        run: cd infra/docker_compose && docker compose down